POST http://localhost:3000/add_guitarcategory.test.php
Content-Type: application/x-www-form-urlencoded

categoryID=100&categoryCode=GTR&categoryName=Guitars&aisleNumber=A1
###
POST http://localhost:3000/add_guitarcategory.test.php
Content-Type: application/x-www-form-urlencoded

categoryID=200&categoryCode=BAS&categoryName=Basses&aisleNumber=A2
###
POST http://localhost:3000/add_guitarcategory.test.php
Content-Type: application/x-www-form-urlencoded

categoryID=300&categoryCode=AMP&categoryName=Amps&aisleNumber=B1
###
POST http://localhost:3000/add_guitarcategory.test.php
Content-Type: application/x-www-form-urlencoded

categoryID=400&categoryCode=DRM&categoryName=Drums&aisleNumber=B2
###
POST http://localhost:3000/add_guitarcategory.test.php
Content-Type: application/x-www-form-urlencoded

categoryID=500&categoryCode=ACC&categoryName=Accessories&aisleNumber=C1